name: ✨ Feature Request
description: Create a feature request issue
labels: ["feature", "enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature in detail
      description: Brief description about the feature, use cases, and expected behavior
    validations:
      required: true
  - type: textarea
    id: comments
    attributes:
      label: Any comments
      description: Share any other information that you think is necessary
    validations:
      required: false